/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/data/mockCourses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/course/[id]` | `/course/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/../components/lessons/DialogLesson`; params?: Router.UnknownInputParams; } | { pathname: `/../components/lessons/CardsLesson`; params?: Router.UnknownInputParams; } | { pathname: `/../components/lessons/ScenarioLesson`; params?: Router.UnknownInputParams; } | { pathname: `/../components/lessons/VisualLesson`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/badges` | `/badges`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/courses` | `/courses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/news` | `/news`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tools` | `/tools`; params?: Router.UnknownInputParams; } | { pathname: `/auth/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/services/api`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/data/mockCourses`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screens)'}/course/[id]` | `/course/[id]`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/lessons/DialogLesson`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/lessons/CardsLesson`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/lessons/ScenarioLesson`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/lessons/VisualLesson`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screens)'}/badges` | `/badges`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/courses` | `/courses`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/news` | `/news`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tools` | `/tools`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/services/api`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/data/mockCourses${`?${string}` | `#${string}` | ''}` | `${'/(screens)'}/course/[id]${`?${string}` | `#${string}` | ''}` | `/course/[id]${`?${string}` | `#${string}` | ''}` | `/../components/lessons/DialogLesson${`?${string}` | `#${string}` | ''}` | `/../components/lessons/CardsLesson${`?${string}` | `#${string}` | ''}` | `/../components/lessons/ScenarioLesson${`?${string}` | `#${string}` | ''}` | `/../components/lessons/VisualLesson${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(screens)'}/badges${`?${string}` | `#${string}` | ''}` | `/badges${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/courses${`?${string}` | `#${string}` | ''}` | `/courses${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/news${`?${string}` | `#${string}` | ''}` | `/news${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tools${`?${string}` | `#${string}` | ''}` | `/tools${`?${string}` | `#${string}` | ''}` | `/auth/LoginScreen${`?${string}` | `#${string}` | ''}` | `/services/api${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/data/mockCourses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/course/[id]` | `/course/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/../components/lessons/DialogLesson`; params?: Router.UnknownInputParams; } | { pathname: `/../components/lessons/CardsLesson`; params?: Router.UnknownInputParams; } | { pathname: `/../components/lessons/ScenarioLesson`; params?: Router.UnknownInputParams; } | { pathname: `/../components/lessons/VisualLesson`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/badges` | `/badges`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/courses` | `/courses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/news` | `/news`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tools` | `/tools`; params?: Router.UnknownInputParams; } | { pathname: `/auth/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/services/api`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
